### ISSUE TITLE
containers/src/containers/internal/storage_type.d(50) : Deprecation: Symbol `std.traits.isBasicType(T)` is not visible from module `storage_type`

### ISSUE THREAD

**Issue by timotheecour** [dlang-community/containers#101]
getting these:

containers/src/containers/internal/storage_type.d(50): Deprecation: Symbol `std.traits.isBasicType(T)` is not visible from module `storage_type` because it is privately imported in module `typecons`

in CI:
https://circleci.com/gh/dlang/phobos/6521?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

of this:
https://github.com/dlang/phobos/pull/6178

**Comment by Hackerpilot** [comment]
The fix for this has already been merged but wasn't tagged properly. Closing manually.
