### ISSUE TITLE
Segfault on garbage collection

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang-community/containers#111]
I am running into a weird segfault on garbage collection in `ttree.d`. I'm not doing anything related to manual memory management or the GC in my code, so I think it's safe to assume that I'm not breaking stuff myself.
Here is the backtrace from GDB if it's of any use : [backtrace.txt](https://github.com/dlang-community/containers/files/2028006/backtrace.txt)
The GC goes through some dsymbol destructors to end up in [ttree.d, line 225](https://github.com/dlang-community/containers/blob/v0.8.0-alpha.7/src/containers/ttree.d#L225) where it crashes.

I'm not sure whether containers or dsymbol is to blame for this, I'm posting this here since this is where the crash originates from.

**Comment by ximion** [comment]
Sounds familiar - maybe take a look at https://github.com/dlang-community/containers/pull/107 and see if there is a similar bug in ttree...

**Comment by Hackerpilot** [comment]
The D-Symbol code contains some boolean flags indicating whether or not the symbol owns the parts of the symbols it contains. If any of these are incorrect, you can end up with a situation where more than one symbol destructor tries to call another symbol's destructor. I think this might be a bug in dsymbol.

**Comment by LaurentTreguier** [comment]
I'm coming back to this, and it really puzzles me.
The segfault occurs when trying to access members of `parts` in `DSymbol`. It's exactly like a classic null pointer/already freed memory access... Except (unless I've missed something) `parts` is just a struct, which means it is always automatically allocated in memory, should have a deterministic lifetime, and doesn't seem to ever be shared between `DSymbol` instances or any other class.
Playing a bit in `DSymbol`'s destructor, when the `DSymbol` with a faulty `parts` is destroyed, I can print `parts`'s address (which looks just like any normal memory address), but I can't access any member, like `length` for example.
So it really looks like freed memory access, but I still have no idea how this is possibly happening...

Maybe I should close this issue and re-open it in [dsymbol](https://github.com/dlang-community/dsymbol) ?
