### ISSUE TITLE
Error: cannot implicitly convert expression ~this.registry of type const(ulong) to immutable(uint)

### ISSUE THREAD

**Issue by andre2007** [dlang-community/containers#136]
https://github.com/dlang-community/containers/blob/d2ae06220dc9ca39d8a4fa6c1e3c18d0daa54367/src/containers/unrolledlist.d#L568

This line causes dmd error
Error: cannot implicitly convert expression ~this.registry of type const(ulong) to immutable(uint)

**Comment by andre2007** [comment]
DMD32 D Compiler v2.084.0
Windows, architecture x86_64

**Comment by LaurentTreguier** [comment]
`BookkeepingType` can larger than a `uint`, and changing line 565,
https://github.com/dlang-community/containers/blob/d2ae06220dc9ca39d8a4fa6c1e3c18d0daa54367/src/containers/unrolledlist.d#L565
to
```d
static if (BookkeepingType.sizeof != uint.sizeof)
```
would technically solve the problem

**Comment by Basile-z** [comment]
I'd go for 
```d
static if (BookkeepingType.sizeof < uint.sizeof)
	immutable uint notReg = ~(cast(uint) registry);
else
	immutable uint notReg = cast(uint) (~registry);  
```

**Comment by carun** [comment]
Reproducible with `ldc2-1.13.0-linux-x86_64`
