### ISSUE TITLE
HashMap initialization at compile time

### ISSUE THREAD

**Issue by jblachly** [dlang-community/containers#142]
First, THANK YOU for this library, which has sped my code up by a tremendous amount over dynamic arrays and other build-in structures.  It is overall nicely written and very easy to use; next on my agenda is to learn how to use with stdx.allocator.

I made the mistake of declaring HashMap in a struct thusly

```
struct A
{
    auto myvar = HashMap!(string, int)(256);
    this(...)
    { ... }
}
```

which caused the compiler to emit the cryptic message `Error: static variable instance cannot be read at compile time`. Removing the bucket count param to the constructor changed the error to `Error: cannot interpret HashMap!(string, int, Mallocator, generateHash, true, true) at compile time` which finally clued me in that maybe it cannot initialize ANYTHING at compile time. Changing the struct member declaration simply to `HashMap!(string,int) myvar;` and moving the constructor call to the struct constructor allowed compilation.

Questions:
1. Why can I not initialize HashMap as struct member at compile time? (other data structures in this library can)
2. Is there any other way to handle this besides what I've done?
3. Wow, those error messages are not helpful for the consumer (that's more of a comment, and more of a frontend problem).

**Comment by CyberShadow** [comment]
>     1. Why can I not initialize HashMap as struct member at compile time?

You can. This works:

```d
struct A
{
    auto myvar = HashMap!(string, int)();
}
```

> Is there any other way to handle this besides what I've done?

What you've done is the best solution.

> Wow, those error messages are not helpful for the consumer (that's more of a comment, and more of a frontend problem).

The first error message points at a limitation of std.experimental.allocator. Maybe it could be avoided by making `instance` a static property function instead of a static variable; then, at least, `GCAllocator` maybe could be usable at compile-time.

I can't reproduce the second error message, maybe a compiler or library update fixed it.
