### ISSUE TITLE
UnrolledList -Wstringop-overflow

### ISSUE THREAD

**Issue by jblachly** [dlang-community/containers#151]
GDC (but not DMD or LDC) gives the following warning:

```
/home/james/.dub/packages/emsi_containers-0.8.0-alpha.13/emsi_containers/src/containers/unrolledlist.d: In function ‘mergeNodes’:
/home/james/.dub/packages/emsi_containers-0.8.0-alpha.13/emsi_containers/src/containers/unrolledlist.d:553:3: warning: ‘__builtin_memcpy’ reading 64 bytes from a region of size 32 [-Wstringop-overflow=]
   first.items[0 .. i] = temp[0 .. i];
```
(corresponds to line 557 in current version)

I instantiated the UnrolledList as:

`new UnrolledList!(myType *);`

That's about as far as I can go. HTH.

**Comment by CyberShadow** [comment]
Does adding `assert(i < nodeCapacity);` before that line help?

**Comment by CyberShadow** [comment]
GDC is currently in a bit of a rut, and supporting it is currently somewhat onerous. Let's reopen this when it becomes clear that this is still an actionable issue. Thanks!
