### ISSUE TITLE
unrolledlist.d unittest fails at line 637

### ISSUE THREAD

**Issue by geert56** [dlang-community/containers#164]
UnrolledList!ubyte incorrectly keeps track of its registry bitvector. It will use a ulong to record the 48 items that can be stored in a single Node. At line 569 notReg is incorrectly calculated, at least on 32-bit architectures. The originally code reads:

```
			static if (BookkeepingType.sizeof < uint.sizeof)
				immutable uint notReg = ~(cast(uint) registry);
			else
			        immutable uint notReg = cast(uint) (~registry);
```

The fixed code might read:

```
			static if (BookkeepingType.sizeof < uint.sizeof)
				immutable uint notReg = ~(cast(uint) registry);
			else
			        immutable ulong notReg = ~registry;
```
Clearly casting a 64-bit ulong to a 32-bit uint causes trouble.

**Comment by rikkimax** [comment]
https://github.com/dlang-community/containers/blob/master/src/containers/unrolledlist.d#L569

>  * Nodes are (by default) sized to fit within a 64-byte cache line. The number
>  * of items stored per node can be read from the $(B nodeCapacity) field.

Has this exhibited a bug in your code? Because if that comment holds true, then casting to uint is perfectly fine.

**Comment by geert56** [comment]
In my case on CentOS 6 32-bit, I can get 48 ubytes in a 64-byte cache line.
Note 2 pointers equals 8 bytes (4 byte pointer on 32-bit arch.). The equation becomes:
64 - (2*4) - 8(ulong) = 48. The 48 items in a Node will need a ulong bitvector. You cannot cast that to a 32-bit uint. On my system this is really a bug.

**Comment by aminya** [comment]
This also fails on x64. See #175

**Comment by geert56** [comment]
I have fixed the bug in my own copy of the source. I have no interest to file a pull request. Go ahead and do so using my suggested solution.

**Comment by aminya** [comment]
I gave an explanation on the error in https://github.com/dlang-community/containers/issues/175#issuecomment-905015444
