### ISSUE TITLE
-betterC ? A question out of curiosity

### ISSUE THREAD

**Issue by geert56** [dlang-community/containers#165]
I am not able to compile any container usage with dmd -betterC.
Am I missing something? I was under the impression that containers was meant as
an alternative for the standard (Phobos) containers.
But I do see use of throw in some files and that clashes with betterC I understand. 
Thanks for any reply.

**Comment by rikkimax** [comment]
Out of scope.

This project (although using the older design for std.experimental.allocators via a dub package) is meant to be able to work with the GC when the druntime is compiled in.

-betterC did not exist when this project began.

A couple that I managed to find quickly on the dub repository: https://github.com/aferust/bcaa https://github.com/aferust/dvector

**Comment by geert56** [comment]
Thank you very much. All I wanted to know.
