### ISSUE TITLE
Can we release a v0.8.1?

### ISSUE THREAD

**Issue by Panke** [dlang-community/containers#167]
I've just ran into the issue that data is not correctly initialized in DynamicArray.resize, which is already fixed in master but not yet released. Can we make a new release? The original fix is almost 6 month old.

**Comment by aminya** [comment]
Tagging @WebFreak001 usually helps. There are a couple of pull requests that need attention as well.

**Comment by aminya** [comment]
Thank you for releasing a new version! @WebFreak001 It would be great if you and others can take a look at the open pull requests! 

https://github.com/dlang-community/containers/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by rikkimax** [comment]
Looks like nobody is taking ownership of the repo and Travis needs to go before any real changes can be had.

So if anyone wants to take that on, I'll merge.

**Comment by aminya** [comment]
@rikkimax I made a PR for using GitHub Actions. #174
