### ISSUE TITLE
Some common interfaces are missing

### ISSUE THREAD

**Issue by yshui** [dlang-community/containers#63]
For example, HashMap doesn't have .byKey, .byValue, HashSet doesn't have opApply, etc.

Are those deliberately left out, or are there plans to implement them in the future? If it's the latter case, are you accepting pull requests? I really want to contribute to this project.

**Comment by Hackerpilot** [comment]
> If it's the latter case, are you accepting pull requests?
https://github.com/economicmodeling/containers/pulls?q=is%3Apr+is%3Aclosed

**Comment by Hackerpilot** [comment]
The changes included in #104 add a lot of methods to the containers including `byKey` and `byValue`. I've removed opApply from the containers and `byKeyValue` should be used instead.

**Comment by BBasile** [comment]
Those referenced in the first message are here now. Open specific issues with the expected function names if any remain.
