### ISSUE TITLE
Moving to dlang-community

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/containers#81]
From https://github.com/dlang-community/D-Scanner/pull/458#issuecomment-308685561

>> Btw don't mind the test failure on dmd-nightly for now - it's a known regression in EMSI containers.
>  Anyway, I think we should also bring emsi_containers to the org, so we can more easily manage such issues.

@Hackerpilot what's your opinion on this?

**Comment by dushibaiyu** [comment]
It is great!

**Comment by wilzbach** [comment]
Ping @HackerPilot

The last commit was nine months ago and there are a couple of good, pending PRs...

**Comment by Hackerpilot** [comment]
I checked with my managers and they don't have any strong feelings one way or the other.

**Comment by wilzbach** [comment]
> I checked with my managers and they don't have any strong feelings one way or the other.

Great - this means there nothing is stopping us from moving this to dlang-community?
You still have the required permissions, correct?

**Comment by wilzbach** [comment]
Friendly piing @Hackerpilot

**Comment by WebFreak001** [comment]
ping @Hackerpilot 

I think when the D community is able to merge PRs and close issues it would greatly benefit everyone because this is also used in some pretty important libraries like libdparse

**Comment by wilzbach** [comment]
Ping @Hackerpilot - the PRs are still open over more than one year and D community would be able to take of maintenance PRs.

**Comment by wilzbach** [comment]
Thanks a lot!

**Comment by Hackerpilot** [comment]
I have the URL on code.dlang.org updated, but nothing else has been updated.

**Comment by wilzbach** [comment]
> I have the URL on code.dlang.org updated, but nothing else has been updated.

OK, I started e.g. here https://github.com/dlang-community/D-Scanner/pull/551

BTW I don't want to appear greedy, but could we use this window of opportunity to move [libddoc](https://github.com/economicmodeling/libddoc) to dlang-community too?
D-Scanner which uses libddoc, is is part of the Jenkins Project Tester since a while now and while it rarely happens, but sometimes e.g. after fixed ugly compiler bugs, updates to some of the tested projects are necessary and then it's quite advantageous if multiple people have commit access.

**Comment by wilzbach** [comment]
Thanks. For now I did the following:
- enabled the repos on Travis
- configured dlang-bot for auto-merge
- updated the URL in the dub.sdl/json files
- fixed the URLs in the containers README

**Comment by ZombineDev** [comment]
Thanks @Hackerpilot! Having all the repos under a single organization makes maintenance much easier and scalable for the community.
