### ISSUE TITLE
HashSet compile error with 2.077.0

### ISSUE THREAD

**Issue by rracariu** [dlang-community/containers#86]
This example:

```
void main()
{
 static struct Foo {}
 import containers.hashset : HashSet;
 HashSet!Foo set; 
}
```

Fails to compile with:

> ..\..\..\Users\x\AppData\Roaming\dub\packages\emsi_containers-0.5.3\emsi_containers\src\containers\hashset.d(503): Error: cast(BucketNode*)current is not an lvalue
..\..\..\Users\x\AppData\Roaming\dub\packages\emsi_containers-0.5.3\emsi_containers\src\containers\hashset.d(337): Error: cast(Bucket[])oldBuckets is not an lvalue
..\source\app.d(76): Error: template instance containers.hashset.HashSet!(Foo, Mallocator, generateHash, false) error instantiating

**Comment by BBasile** [comment]
Works For Me
