### ISSUE TITLE
readme link does not work http://economicmodeling.github.io/containers/index.html

### ISSUE THREAD

**Issue by timotheecour** [dlang-community/containers#90]
404
There isn't a GitHub Pages site here.

**Comment by wilzbach** [comment]
Thanks for the FYI -> https://github.com/dlang-community/containers/pull/92

**Comment by wilzbach** [comment]
If someone wants to, we could setup Travis to update the documentation automatically: https://gist.github.com/veelo/f7668510bad2e8c9212ab66104541fcc

PRs welcome.
