### ISSUE TITLE
DynamicArray should not call destructors for objects

### ISSUE THREAD

**Issue by n8sh** [dlang-community/containers#96]
A `DynamicArray` whose elements are objects calls `destroy` on them in `remove` and `~this`. If any other references remain to those objects this will cause memory corruption.

I hope no one was relying on this functionality, but if anyone was it could be solved by creating a tag before applying the fix.

Pull request with fix: https://github.com/dlang-community/containers/pull/97

**Comment by BBasile** [comment]
Yes. It should only be done for struct and unions.
